# Config file for automatic testing at travis-ci.org
#  Hello
language: python
matrix:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  include:
    - python: "2.7"
      env: TOXENV=py27,docs,style
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36

before_install:
  - sudo apt-get update -qq
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox 
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
 # - tox -e $TOXENV
notifications:
  email:
    on_success: never
    on_failure: always
webhooks:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always

